version: '3'
services:
  mariadb:
    image: mariadb
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      MYSQL_DATABASE: qr_app
      MYSQL_USER: root
      MYSQL_PASSWORD:
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - ../backend/bd/qr_app.sql/:/docker-entrypoint-initdb.d/qr_app.sql
  api:
    build: ../backend/api
    container_name: api
    ports:
      - 3000:3000
  angular:
    build: ../frontend
    container_name: angular
    ports:
      - 4200:4200
